server:
  undertow:
    threads:
      io: 16           # I/O threads (Usually cores * 2)
      worker: 200      # Worker threads (Virtual threads handle the heavy load)
    buffer-size: 1024  # Direct buffer optimization
    direct-buffers: true

spring:
  application:
    name: url-shortener-native

app:
  shortener:
    salt: "my-secret-salt-change-me-in-prod" # Should be an env var in production
  
  # JAVA 21+ MAGIC
  threads:
    virtual:
      enabled: true  # Enables Virtual Threads across the container (Undertow)

  # Optimized Configuration for Cassandra and Redis
  cassandra:
    keyspace-name: url_shortener
    local-datacenter: datacenter1
    connection:
      connect-timeout: 2s
      init-query-timeout: 2s
    schema-action: create-if-not-exists
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
