server:
  undertow:
    threads:
      io: 16           # I/O threads (Usually cores * 2)
      worker: 200      # Worker threads (Virtual threads handle the heavy load)
    buffer-size: 1024  # Direct buffer optimization
    direct-buffers: true

spring:
  application:
    name: url-shortener-native
  threads:
    virtual:
      enabled: true  # Enables Virtual Threads across the container (Undertow)

app:
  shortener:
    salt: "my-secret-salt-change-me-in-prod" # Should be an env var in production

  # Optimized Configuration for Cassandra and Redis
  cassandra:
    keyspace-name: url_shortener
    local-datacenter: datacenter1
    connection:
      connect-timeout: 2s
      init-query-timeout: 2s
    schema-action: create-if-not-exists
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, circuitbreakers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
  health:
    circuitbreakers:
      enabled: true

rate-limiter:
  limit: 60
  window: PT1M

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      rateLimiterCb:
        baseConfig: default
        failureRateThreshold: 40
        waitDurationInOpenState: 10s
      databaseCb:
        baseConfig: default
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
